version: '2'
services:
  db:
    image: mysql:5.7.18
    environment:
    - MYSQL_ROOT_PASSWORD=a
    volumes:
      - ./data:/data
      - data-volume:/var/lib/mysql
    command: ["mysqld", "--secure-file-priv=/data"]
  load:
    image: shusson/variantloader:1.0
    entrypoint: 'go-wrapper run -c -d "root:a@tcp(db:3306)/"'
  api:
    image: shusson/variantstore:1.0
    ports:
      - "8080:8080"
    entrypoint: 'go-wrapper run -d "root:a@tcp(db:3306)/v"'

volumes:
  data-volume:
